
import Myframe.*;
import java.awt.Frame;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();  
       
        DangNhap f = new DangNhap();
          Desktop.add(f);
        f.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        DangNhap = new javax.swing.JMenuItem();
        menuFile = new javax.swing.JMenu();
        DangKy = new javax.swing.JMenuItem();
        BanHang = new javax.swing.JMenuItem();
        QLSP = new javax.swing.JMenuItem();
        QLLSP = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        HD_HDCT = new javax.swing.JMenuItem();
        QLKho = new javax.swing.JMenuItem();
        QLNV = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        jMenu3.setText("Đăng nhập");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Left.png"))); // NOI18N
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        DangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Unknown person.png"))); // NOI18N
        DangNhap.setText("Đăng nhập");
        DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangNhapActionPerformed(evt);
            }
        });
        jMenu3.add(DangNhap);

        jMenuBar2.add(jMenu3);

        menuFile.setText("Nhân viên");

        DangKy.setText("Đăng ký");
        DangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangKyActionPerformed(evt);
            }
        });
        menuFile.add(DangKy);

        BanHang.setText("Bán hàng");
        BanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanHangActionPerformed(evt);
            }
        });
        menuFile.add(BanHang);

        QLSP.setText("Quản lý Sản phẩm");
        QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLSPActionPerformed(evt);
            }
        });
        menuFile.add(QLSP);

        QLLSP.setText("Quản lý loại sản phẩm");
        QLLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLLSPActionPerformed(evt);
            }
        });
        menuFile.add(QLLSP);

        jMenuBar2.add(menuFile);

        jMenu4.setText("Quản lý");

        HD_HDCT.setText("Hóa Đơn_HDCT");
        HD_HDCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HD_HDCTActionPerformed(evt);
            }
        });
        jMenu4.add(HD_HDCT);

        QLKho.setText("Quản lý kho");
        QLKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLKhoActionPerformed(evt);
            }
        });
        jMenu4.add(QLKho);

        QLNV.setText("Quản lý nhân viên");
        QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLNVActionPerformed(evt);
            }
        });
        jMenu4.add(QLNV);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangKyActionPerformed
        DangKy f=new DangKy();
      Desktop.add(f);
      f.setVisible(true);
    }//GEN-LAST:event_DangKyActionPerformed

    private void QLLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLLSPActionPerformed
       QuanLyLoaiSP f =new QuanLyLoaiSP();
       Desktop.add(f);
       f.setVisible(true);
    }//GEN-LAST:event_QLLSPActionPerformed

    private void BanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanHangActionPerformed
        BanHang f = new BanHang();
        Desktop.add(f);
        f.setVisible(true);
                
    }//GEN-LAST:event_BanHangActionPerformed

    private void QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLSPActionPerformed
        QLSP f = new QLSP();
         Desktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_QLSPActionPerformed

    private void QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLNVActionPerformed
       QLNV f = new QLNV();
        Desktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_QLNVActionPerformed

    private void DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangNhapActionPerformed
        DangNhap f = new DangNhap();
          Desktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_DangNhapActionPerformed

    private void HD_HDCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HD_HDCTActionPerformed
        HD_HDCT f =new HD_HDCT();
            Desktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_HD_HDCTActionPerformed

    private void QLKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLKhoActionPerformed
        QLKHo f = new QLKHo();
         Desktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_QLKhoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BanHang;
    private javax.swing.JMenuItem DangKy;
    private javax.swing.JMenuItem DangNhap;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem HD_HDCT;
    private javax.swing.JMenuItem QLKho;
    private javax.swing.JMenuItem QLLSP;
    private javax.swing.JMenuItem QLNV;
    private javax.swing.JMenuItem QLSP;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu menuFile;
    // End of variables declaration//GEN-END:variables
}
